language: go
sudo: false
install:
- go get -v ./...
- GO111MODULE=off go get golang.org/x/tools/cmd/goimports
env:
  global:
  - GO111MODULE=on
go:
- 1.13
- 1.14
- 1.15
- tip
before_script:
- go vet ./...
- go test -v ./...
script:
- ./script/format
